examen/urls.py
from django.conf.urls import url,include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^',include('inspeccion.urls', namespace='inspeccion')),
]

inspeccion/urls.py
from django.conf.urls import url, include
from inspeccion.views import ListaCentros, NuevoCentro, EditarCentro, EliminarCentro, lista_vehiculos, nuevo_vehiculo, editar_vehiculo, eliminar_vehiculo, NuevaInspeccion
from . import views

urlpatterns = [
	url(r'centros/$', ListaCentros.as_view(), name = 'listacentros'),
	url(r'centros/nuevo/$', NuevoCentro.as_view(), name = 'nuevocentro'),
	url(r'centros/editar/(?P<id>[0-9]+)/$', EditarCentro.as_view(), name = 'editarcentro'),
	url(r'centros/eliminar/$', EliminarCentro.as_view(), name = 'eliminarcentro'),
	url(r'vehiculos/$', views.lista_vehiculos, name='listavehiculos'),
	url(r'vehiculos/nuevo/$', views.nuevo_vehiculo, name = 'nuevovehiculo'),
	url(r'vehiculos/editar/(?P<id>[0-9]+)/$', views.editar_vehiculo, name = 'editarvehiculo'),
	url(r'vehiculos/eliminar/$', views.eliminar_vehiculo, name = 'eliminarvehiculo'),
	url(r'inspeccion/nueva/$', NuevaInspeccion.as_view(), name = 'nuevainspeccion'),
	url('^$',views.index, name= 'index'),
	url(r'registration/', include('django.contrib.auth.urls')),



				
]

inspeccion/models.py
from __future__ import unicode_literals

from django.db import models


class Centro(models.Model):
	nombre = models.CharField(max_length=100)
	id_centro = models.IntegerField()
	def __str__(self):
		return self.nombre

class Vehiculo(models.Model):
	nombre = models.CharField(max_length=100)
	id_vehiculo = models.IntegerField()

	def __str__(self):
		return self.nombre

class Inspeccion(models.Model):
	fecha_inspeccion = models.DateField()
	Centro = models.ForeignKey(Centro , on_delete = models.CASCADE)
	Vehiculo = models.ForeignKey(Vehiculo , on_delete = models.CASCADE)

inspeccion/forms.py
from django.forms import ModelForm
from inspeccion.models import Centro, Vehiculo, Inspeccion

class CentroForm(ModelForm):
	class Meta:
		model = Centro
		exclude = ()

class VehiculoForm(ModelForm):
	class Meta:
		model = Vehiculo
		exclude = ()

class InspeccionForm(ModelForm):
	class Meta:
		model = Inspeccion
		exclude = ()

inspeccion/views.py
from django.shortcuts import render, redirect, reverse, get_object_or_404
from django.contrib.auth.views import redirect_to_login
from django.views import View
from inspeccion.models import Centro, Vehiculo
from inspeccion.forms import CentroForm, VehiculoForm, InspeccionForm
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models import Sum

# Create your views here.


class ListaCentros(View):
	template_name = 'inspeccion/lista_centros.html'

	def get(self, request, *args, **kwargs):
		centros = Centro.objects.all()
		return render(request, self.template_name, { 'centros' : centros })


class NuevoCentro(View):
	template_name = 'inspeccion/editar_centro.html'
	form_class = CentroForm

	def get(self, request, *args, **kwargs):
		form = self.form_class()
		return render(request, self.template_name, { 'form' : form })

	def post(self, request, *args, **kwargs):
		form = self.form_class(request.POST)

		if form.is_valid():
			form.save()
			return redirect(reverse('inspeccion:listacentros'))

		return render(request, self.template_name, { 'form' : form })

	def dispatch(self, *args, **kwargs):
		if self.request.user.is_staff:
			return super(NuevoCentro, self).dispatch(*args, **kwargs)
		else:
			return redirect_to_login(reverse('inspeccion:nuevocentro'))





class EditarCentro(View):
	template_name = 'inspeccion/editar_centro.html'
	form_class = CentroForm

	def get(self, request, *args, **kwargs):
		c_id = kwargs['id']
		c = get_object_or_404(Centro, pk = c_id)
		if not c:
			return redirect(reverse('inspeccion:listacentros'))

		form = self.form_class(instance = c)
		return render(request, self.template_name, { 'form' : form })

	def post(self, request, *args, **kwargs):
		c_id = kwargs['id']
		c = get_object_or_404(Centro, pk = c_id)
		if not c:
			return redirect(reverse('inspeccion:listacentros'))
		form = self.form_class(request.POST, instance = c)

		if form.is_valid():
			form.save()
			return redirect(reverse('inspeccion:listacentros'))

		return render(request, self.template_name, { 'form' : form })

	def dispatch(self, *args, **kwargs):
		if self.request.user.is_staff:
			return super(EditarCentro, self).dispatch(*args, **kwargs)
		else:
			return redirect_to_login(reverse('inspeccion:editarcentro', kwargs = { 'id' : kwargs['id'] }))




class EliminarCentro(View):

	def get(self, request, *args, **kwargs):
		return redirect(reverse('inspeccion:listacentros'))

	def post(self, request, *args, **kwargs):
		c_id = request.POST.get('id')
		c = get_object_or_404(Centro, pk = c_id)
		c.delete()
		return redirect(reverse('inspeccion:listacentros'))

	def dispatch(self, *args, **kwargs):
		if self.request.user.is_staff:
			return super(EliminarCentro, self).dispatch(*args, **kwargs)
		else:
			return redirect_to_login(reverse('inspeccion:listacentros'))









def lista_vehiculos(request):
	template_name = 'inspeccion/lista_vehiculos.html'

	if request.method == 'GET':
		
		vehiculos = Vehiculo.objects.all()

		return render(request, template_name, { 'vehiculos' : vehiculos })




def nuevo_vehiculo(request):
	template_name = 'inspeccion/editar_vehiculo.html'
	form_class = VehiculoForm

	
	if request.method == 'POST':
		form = form_class(request.POST)

		if form.is_valid():
			form.save()
			return redirect(reverse('inspeccion:listavehiculos'))
	else:
		form = form_class()
	return render(request, template_name, { 'form' : form })





def editar_vehiculo(request, id):
	template_name = 'inspeccion/editar_vehiculo.html'
	form_class = VehiculoForm

	if not request.user.is_staff:
		return redirect_to_login(reverse('inspeccion:editarvehiculo', kwargs = { 'id' : id }))

	vehiculo = get_object_or_404(Vehiculo, pk = id)
	if not vehiculo:
		return redirect(reverse('inspeccion:listavehiculos'))

	if request.method == 'POST':
		form = form_class(request.POST, instance = vehiculo)

		if form.is_valid():
			form.save()
			return redirect(reverse('inspeccion:listavehiculos'))
	else:
		form = form_class(instance = vehiculo)
	return render(request, template_name, { 'form' : form })





def eliminar_vehiculo(request):
	idvehiculo = request.POST.get('id')
	vehiculo = get_object_or_404(Vehiculo, pk = idvehiculo)
	idcir = vehiculo.centro.id

	if not request.user.is_staff:
		return redirect_to_login(reverse('inspeccion:listavehiculos', kwargs = { 'idcir' : idcir }))

	if request.method == 'POST':
		vehiculo.delete()
		
	return redirect(reverse('inspeccion:listavehiculos', kwargs = { 'idcir' : idcir }))



class NuevaInspeccion(View):
	template_name = 'inspeccion/nueva_inspeccion.html'
	form_class = InspeccionForm

	def get(self, request, *args, **kwargs):
		form = self.form_class()
		return render(request, self.template_name, { 'form' : form })

	def post(self, request, *args, **kwargs):
		form = self.form_class(request.POST)

		if form.is_valid():
			form.save()
			return redirect(reverse('inspeccion:listacentros'))

		return render(request, self.template_name, { 'form' : form })

	def dispatch(self, *args, **kwargs):
		if self.request.user.is_staff:
			return super(NuevaInspeccion, self).dispatch(*args, **kwargs)
		else:
			return redirect_to_login(reverse('inspeccion:nuevainspeccion'))





def index(request):
	template_name = 'inspeccion/index.html'
	
	return render(request, template_name)

inspeccion/templates/inspeccion/editar_centro.html
{% extends "base.html" %}

{% block title %}Editar centro{% endblock title %}

{% block content %}
<h3>Editar centro</h3>
<form id='form' method='post' enctype='multipart/form-data' action=''>{% csrf_token %}
			    {{form.as_p}}
				<p><input type='submit' value='Guardar'></p>
</form>
{% endblock content %}

inspeccion/templates/inspeccion/editar_vehiculo.html
{% extends "base.html" %}

{% block title %}Editar vehiculo{% endblock title %}

{% block content %}
<h3>Editar vehiculo</h3>
<form id='form' method='post' enctype='multipart/form-data' action=''>{% csrf_token %}
			    {{form.as_p}}
				<p><input type='submit' value='Guardar'></p>
</form>
{% endblock content %}

inspeccion/templates/inspeccion/index.html
{%extends 'base.html'%}
{%block title %}Pagina principal{%endblock%}

{%block content %}<h3>Bienvenido</h3>{%endblock%}

inspeccion/templates/inspeccion/lista_centros.html
{% extends "base.html" %}

{% block title %}Inspeccion{% endblock title %}

{% block content %}
<h3>Listado de centros</h3>
{% if centros %}
	<ul>
	{% for c in centros %}
		<li><a href="{% url 'inspeccion:listacentros' %}">{{ c.nombre }}</a>
		{% if request.user.is_staff %}
		<small><a href="{% url 'inspeccion:editarcentro' c.id %}">Editar</a></small>
		<form style="display:inline" action="{% url 'inspeccion:eliminarcentro' %}" method="POST">
			{% csrf_token %}
			<input type="hidden" value="{{ c.id }}" name="id">
			<button onclick="return confirm('Desea eliminar esta circunscripción?');" type="submit">Eliminar</button>
		</form>
		{% endif %}
		</li>
	{% endfor %}
	</ul>
{% else %}
	<p>No existe ningun centro.</p>
{% endif %}
{% if request.user.is_staff %}
	<small><a href="{% url 'inspeccion:nuevocentro' %}">Añadir centro</a></small>
{% endif %}
{% endblock content %}

inspeccion/templates/inspeccion/lista_vehiculos.html
{% extends "base.html" %}

{% block title %}Inspeccion{% endblock title %}

{% block content %}
<h3>Listado de vehiculos</h3>
{% if vehiculos %}
	<ul>
	{% for c in vehiculos %}
		<li><a href="{% url 'inspeccion:listavehiculos' %}">{{ c.nombre }}</a>
		{% if request.user.is_staff %}
		<small><a href="{% url 'inspeccion:editarvehiculo' c.id %}">Editar</a></small>
		<form style="display:inline" action="{% url 'inspeccion:eliminarvehiculo' %}" method="POST">
			{% csrf_token %}
			<input type="hidden" value="{{ c.id }}" name="id">
			<button onclick="return confirm('Desea eliminar esta circunscripción?');" type="submit">Eliminar</button>
		</form>
		{% endif %}
		</li>
	{% endfor %}
	</ul>
{% else %}
	<p>No existe ningun vehiculo.</p>
{% endif %}
{% if request.user.is_staff %}
	<small><a href="{% url 'inspeccion:nuevovehiculo' %}">Añadir vehiculo</a></small>
{% endif %}
{% endblock content %}

inspeccion/templates/inspeccion/nueva_inspeccion.html
{% extends "base.html" %}

{% block title %}Nueva inspeccion{% endblock title %}

{% block content %}
<h3>Nueva inspeccion</h3>
<form id='form' method='post' enctype='multipart/form-data' action=''>{% csrf_token %}
			    {{form.as_p}}
				<p><input type='submit' value='Guardar'></p>
</form>
{% endblock content %}

templates/base.html
<!DOCTYPE html>
<html>
<head>
  <title>{% block title %}Inspeccion{% endblock %}</title>
</head>
<body>

<div class="container">
<ul>
	<li><a href="{%url 'inspeccion:listacentros'%}">Lista de centros</a></li>

	<li><a href="{%url 'inspeccion:listavehiculos'%}">Lista de vehiculos</a></li>

	<li><a href="{%url 'inspeccion:nuevainspeccion'%}">Nueva inspeccion</a></li>


	{%if user.is_anonymous%}

	<li><a href="{%url 'inspeccion:login'%}">Login</a></li>

	{%else%}

	<li>Bienvenido {{user.username}}</li>

	<li><a href="{%url 'inspeccion:logout'%}?next=/">Logout</a></li>

	{%endif%}
</ul>
	{% block content %}{% endblock content %}
</div>
</body>
</html>